### ISSUE TITLE
Refactoring Templates & Java Files

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#51]
## Issue Description
The templates and Java files should have some better structure!

@dsteen338 I remember you mentioned something like this in an earlier PR, how do you think we should organize the Java files?

## Tasks
- [x] Add packages for Java files
- [x] Re-organize & rename some templates
- [x] Rename grid.js to course.js

## Screenshots and Documentation
![image](https://user-images.githubusercontent.com/18077531/31464137-e6e615ca-aea6-11e7-9c57-d574518fd1b7.png)

**Comment by dsteen338** [comment]
Well depending on how many classes we will have, we could either re-organize based on modules or not. I don't think we have clearly defined enough modules (at least not yet), so I think we should separate into `entity`, `controller`, and `repository` packages at least. I also think we should refactor the `TrackerController` into multiple `Controller` classes, we might need to follow some steps detailed here to achieve this, detailed here: 

https://smarterco.de/java-spring-boot-mvc-ontroller-not-called/

EDIT: Maybe `Student` and `Instructor` Packages should be at the top level? Will probably need another one on top of those as a catch all for others.

**Comment by dsteen338** [comment]
Another thing that might be useful is creating an `Entity` parent class for all of our objects to extend. This would make it so we don't have to remember to add the field with the correct annotations every time, and may come in handy for some convenience methods using generics.

**Comment by brandon1024** [comment]
This issue was addressed accidentally through the [SWE50 issue](https://github.com/SWE-4103-Group-3/Project/issues/50) :)
