### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#56]
## Issue Description
As a student, I want to be able to search through all of the existing courses to find the right course. There should be some sort of search bar at the top of the dashboard which allows me to query the database display a list of courses on a new page. When I click on one of these courses, I should be taken to the course page.

## Tasks
- [x] Add search bar
- [x] Create results view
- [x] Add the necessary logic to query the database from the search string
