### ISSUE TITLE
Create Release template, guide and wrap up + deploy first release

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#58]
## Issue Description
We need to have a list of steps to wrap up a release and then deploy it

## Tasks
- [x] Decide on a version number
    - https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401
- [x] Create release branch/ tag
- [x] Ensure all code is merged onto said branch
- [ ] Test all features
- [x] Ensure build passes
- [x] Compile release notes
- [ ] Write a guide on deploying when deploying
    - **Ensure security issues are addressed before actually doing the deploy** 
- [x] Deploy to somewhere publicly accessible
    - Currently planning to use digital ocean for this

**Comment by dsteen338** [comment]
Here's a good guide I found on wrapping up a release: 

https://www.clearvision-cm.com/blog/8-steps-software-release-management-agile-teams/

**Comment by dsteen338** [comment]
release notes starter: 
https://github.com/SWE-4103-Group-3/Project/wiki/Release-notes

**Comment by mwalz1** [comment]
@dsteen338 can we put a number on this?  maybe a 3?
