### ISSUE TITLE
Course Edit Page

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#63]
## Issue Description
An instructor should be able edit their course information (name, section, times, seating plan, etc). Currently, they are only able to edit the seating template. We should probably create a new view for this.

## Tasks
- [ ] Create new view for editing courses
- [x] Add new endpoint for editing courses
- [x] Complete all of the necessary logic

**Comment by mwalz1** [comment]
@dsteen338 @MackenzieJones 
### Update on requirements for this issue:
1. Heads up we will be slashing the time and end-date fields.
2. Also students are expected to be cleared from the seating-grid when rows & cols are modified.  These students will have to re-choose their seats.
3. Any statistics must remain intact when modifying the course information.
