### ISSUE TITLE
Dr. MacIsaac Changes

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#64]
## Issue Description
These are the changes Dr. MacIsaac wants to see:

## Tasks
- [x] Change Teacher to Instructor
- [x] Required stars for forms (Course-Name, Start-Date, Rows, and Columns)
- [x] Fix course form validation
- [x] ~~Dropdown for sections in course page~~

**Comment by mwalz1** [comment]
After speaking with Dr. MacIsaac, I have confirmed that two instructors should be able to create the same course name and section, as a course is unique from a combination of the two previously mentioned + the instructor name or id.

**Comment by mwalz1** [comment]
@tonerm43 @Korbos 
### Update to Issue Requirements.
1. Get rid of Time-slot and End-date fields.
2. Section is not mandatory, but a course still uses the section field to be considered unique. 
3. Course-Name, Start-Date, Rows, and Columns are all required fields.

**Comment by tonerm43** [comment]
With the additions of sections being shown in the course list, and course edit page, we did not want to clutter the UI so course section dropdown removed from scope for this issue.

**Comment by jacsmith21** [comment]
Can this issue be closed?
