### ISSUE TITLE
Take Attendance Frontend

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#76]
## Issue Description
This issue involves the frontend logic for taking attendance.

## Tasks
- [x] Create attendance, submit and cancel buttons
- [x] Create click logic for grid
- [x] Create the ajax post request method
- [x] Create toaster for success / failure
- [x] Create UI indicator for "absent"

edit: removing json template
